version: '2'
services:
    verifymycandidate-app:
        image: verifymycandidate
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://verifymycandidate-postgresql:5432/verifyMyCandidate
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=verifymycandidate-elasticsearch:9300
        ports:
            - 8080:8080
    verifymycandidate-postgresql:
        extends:
            file: postgresql.yml
            service: verifymycandidate-postgresql
    verifymycandidate-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: verifymycandidate-elasticsearch
